CREATE DATABASE eam_c1 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE eam DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE eam_demo DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE eam_view DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;



utf8mb4_general_ci