CREATE DATABASE eam_c1 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE eam DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE eam_v2 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

